### ISSUE TITLE
Native support for GridFS

### ISSUE THREAD

**Issue by RaymondKirk** [RaymondKirk/topic_store#4]
The database read/writer here 
https://github.com/RaymondKirk/topic_store/blob/e6f0d5698d234234050d2ae04089e5aa0f3d1c6c/src/topic_store/database.py#L22-L130

Needs to be altered to store/return topic_store.data.TopicStore objects. Currently it supports it but not with GridFS, the underlying default database should be changed to navitvly use GridFS to remove storage size restrictions.

Default api is here https://github.com/RaymondKirk/topic_store/blob/e6f0d5698d234234050d2ae04089e5aa0f3d1c6c/src/topic_store/api.py#L22-L61

**Comment by RaymondKirk** [comment]
One easy way may just be to swap out using pymongo.MongoClient with @dreamingraven ezdb.

**Comment by DreamingRaven** [comment]
Will topic store need to handle both standard mongodb documents and gridfs objects? I.E will it still need normal documents for other use cases or is it explicitly for raspberry data collection?

If it only requires gridfs it will be relativeley quick, if it requires both then we will need to change how you call things in code, as we will need to define some way to tell the difference like in ezdb if you give it  atuple of (dict and file-like-object) it will dict-> file metadata like filename, and file-like-object will be serialised and stored int he .files db. Otherwise if you dump just a dict it will use standard mongodb documents.

**Comment by RaymondKirk** [comment]
I think using GridFS is a reasonable default to have, support for only GridFS enabled collections is fine

**Comment by DreamingRaven** [comment]
Yo ray what in the returned dict from ```self.parser(topic_store.dict.copy())``` in insert one will be the big piece of data?

**Comment by DreamingRaven** [comment]
Ok well I tried for 3 hours, not going to go any further with it. I cant test it, or write it without being able to see types, since the types are so important especially to gridfs.

Standard Mongo document insertion to an already running database:
```
from ezdb.mongo import Mongo
db = Mongo() # any option at all as dict listed in https://python-ezdb.readthedocs.io/en/dev/mongo.html#api
db.connect()
db.dump(db_collection_name="test", data={"success": 1})
```
Gridfs document insertion to an already running database:
```
from ezdb.mongo import Mongo
db = Mongo() # any option at all as dict
db.connect()
db.dump(db_collection_name="test", data=({"success": 1}, b'success')) # data = tuple(dictionary_metadata, file_like_object or bytes)
```

In your case the data tuple will be (`your normal dictionary except image`, `the image bytes/file`), but there is little way for me to be able to do this for you, even if it is such a short change.

**Comment by RaymondKirk** [comment]
> Yo ray what in the returned dict from `self.parser(topic_store.dict.copy())` in insert one will be the big piece of data? We will store that as the file and the rest as a standard dict, conserving the 16MB limit, but allowing aggregation.

That bit of info is unknown because the dict is a rich hierarchy of key value pairs of which could be 10B or 10MB, maybe GridFS won't be flexible enough for our use case. Maybe it would be better to just chunk it into different documents ourselves?

**Comment by RaymondKirk** [comment]
Otherwise should we just dynamically make all non-python types (list, set, int, float etc) in the normal document and everything else into a gridfs chunk?

**Comment by DreamingRaven** [comment]
> That bit of info is unknown because the dict is a rich hierarchy of key value pairs of which could be 10B or 10MB, maybe GridFS won't be flexible enough for our use case. Maybe it would be better to just chunk it into different documents ourselves?

I would strongly advise against us chunking it as it will be horrible to work with, and would just be a bit of wasted effort. Is it not the case tho that the image is the biggest single part of the document? If so we can just always just use the image bytes directly which can be put into gridfs without any issue as io.BytesIO.

> Otherwise should we just dynamically make all non-python types (list, set, int, float etc) in the normal document and everything else into a gridfs chunk?

If it was me, I would keep things as base types as possible, as it makes everything a lot easier, BSON and python dictionaries can almost be 1-to-1, it makes searching the database a lot easier and faster too which is actually a big concern, otherwise aggregation will be an absolute nightmare.

**Comment by DreamingRaven** [comment]
Anyway as a temporary fix we have next-cloud, its not pretty, but it will work for now until such a time as we have figured out a good way to do it. Failing that I can create a short script to back up to the database when a file changes remembering past versions of the file too if desirable.

**Comment by RaymondKirk** [comment]
Added in #5 and improved in #6, ezdb no longer required until later. Strategy for storage not as easy with it so just added the GridFS calls and strat in the database.py/data file.
